# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ky0Q1w1PV6mqIi4WO9NB04FxVhd9oIk
"""

def kunlar(belgi):
  if belgi == "Dushanba":
      return "Trenajor kuni"
  elif belgi == "Seshanba":
      return "Iteach kuni"
  elif belgi == "Chorshanba":
      return "Trenajor kuni"
  elif belgi == "Payshanba":
      return "Kurs kuni"
  elif belgi == "Jum'a":
      return "Trenajor kuni"
  elif belgi == "Shanba kuni":
      return "Iteach va Suxga ketish kuni"
  elif belgi == "Yakshanba":
      return "Suxdagi ishlar bajarish"
  else:
      return "Deyarli har kuni Uqish va shaxsiy ishlar albatta"
belgi = input("kunning nomini kiriting: ")
natija = kunlar(belgi)
print(natija)

